'use strict';

const lus = {
    LIBUSB_REQUEST_TYPE_VENDOR: (0x02 << 5),
    LIBUSB_RECIPIENT_DEVICE: 0,
    LIBUSB_ENDPOINT_IN: 0x80,
    LIBUSB_ENDPOINT_OUT: 0
};

module.exports = {
    FTDI_REQTYPE_OUT: lus.LIBUSB_REQUEST_TYPE_VENDOR |
        lus.LIBUSB_RECIPIENT_DEVICE |
        lus.LIBUSB_ENDPOINT_OUT,
    FTDI_IFC_A: 1,
    FTDI_IFC_B: 2,
    FTDI_CTL_RESET:         0,
    FTDI_CTL_SET_BITMODE:   0x0b,
    FTDI_CTL_SET_EVENT_CH:  0x06,
    FTDI_CTL_SET_ERROR_CH:  0x07
};
